### ISSUE TITLE
Looks like there is some problem with Informix bigserial data type

### ISSUE THREAD

**Issue by JosefMachytka-credativ** [psoo/informix_fdw#1]
Hello, I am investigating problem one of our clients has with informix_fdw. They have tables with bigserial column and some of values are shown as negative values in PostgreSQL foreing tables (informix 12, pg 13, informix_fdw 0.5.3). I was not able to repeat their problem, but I found some different problem with bigserial informix data type (tested on informix 12 and all combinations of PG 12,13,15 and informix_fdw 0.5.3 and 0.6.0).

I created manually Informix table:

CREATE TABLE IF NOT EXISTS "dwa".ean_n_values
  (
    ean_n_id bigserial not null,
    iean140 real,
    iean150 smallint,
    iean190 char(4) not null
  );

And inserted data - tried manual insert commands and also load from unl file. Data in Informix look OK, I can see all values as expected. Then I used import schema (PostgreSQL foreign table has bigint data type) and If I try to select using informix_fdw from Informix table, I get an error in PostgreSQL:

ERROR:  invalid input syntax for type bigint: "                     "

And dbeaver shows me these details for the error:

org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [22P02]: ERROR: invalid input syntax for type bigint: "                     "
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
        at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:187)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
        at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5140)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: invalid input syntax for type bigint: "                     "
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
        ... 7 more

I tried to read informix table with bigserial column using foreign table with text data type and it shows string containing 21 spaces instead of bigserial informix value. I.e. this is consistent with the error message I got.

When I repeat this test with bigint data type in Informix table, all works as expected and PostgreSQL can read informix data.

Looks like there is some problem specifically with Informix bigserial data type. Do you know if this could be influenced by some settings? Or if there is some workaround for these problems?
Thank you.

**Comment by psoo** [comment]
I am going to look into this asap.

**Comment by psoo** [comment]
Ok, there is sth going on really strange here.

We have this in our regression test suite that stresses the same use case you've here, this way:

Informix table:

````
create table "informix".bigserial_test 
  (
    id bigserial not null ,
    v1 varchar(20) not null ,
    primary key (id) 
  );
````

PostgreSQL definition looks like (taken from the source in `sql/informix_fdw_tx.sql` 

````
--
-- Foreign table to test BIGSERIAL values
--
CREATE FOREIGN TABLE bigserial_test(id bigserial not null, v1 varchar(20) not null)
SERVER test_server
OPTIONS("table" 'bigserial_test',
                client_locale :'CLIENT_LOCALE',
                db_locale :'DB_LOCALE',
                database :'INFORMIXDB');

--------------------------------------------------------------------------------
-- DML for BIGSERIAL values
--------------------------------------------------------------------------------

BEGIN;

-- NOTE: the 0 value will advance the informix sequence.

INSERT INTO bigserial_test(id, v1) VALUES(0, 'abc');
INSERT INTO bigserial_test(id, v1) VALUES(0, 'def');
INSERT into bigserial_test values(9223372036854775807, 'ghi');

SELECT * FROM bigserial_test ORDER BY id ASC;

-- DELETE INT8_MAX value
DELETE FROM bigserial_test WHERE id = 9223372036854775807;

SELECT * FROM bigserial_test ORDER BY id ASC;

-- DELETE all
DELETE FROM bigserial_test;

-- empty set expected
SELECT * FROM bigserial_test ORDER BY id ASC;

COMMIT;
````

These test passes perfectly without any issues.

I need to dive into it, to examine why the code doesn't work in your particular case, but i have a suspicion...

**Comment by JosefMachytka-credativ** [comment]
I see, but it looks to me like you are in that test inserting data using informix_fdw from PostgreSQL into Informix empty table.
I have a docker lab with Informix 12 container and first insert data directly into Informix and try to read them from PostgreSQL 12/13/15 on Ubuntu 20 (client has this OS). 

But true is than first tests with iwadb informix testing database from github also did not show any problems. Only additional manual tests gave this error. Could it be influenced by some settings, like locale?

--------------------------------------------- Informix part: ----------------------------------------------------
    image: ibmcom/informix-developer-database:12.10.FC12W1DE
    container_name: informix
    hostname: informix
    environment:
      - LICENSE=accept
      - SIZE=small
      - DB_LOCALE=en_US.utf8
      - CLIENT_LOCALE=en_US.utf8


****** create_testdb.sh (running inside Informix container)

#!/bin/bash

echo "--> start-up"

DB_NAME=testdb
DB_SPACE=rootdbs
CONFIGPATH=/scripts/
BINPATH=/opt/ibm/informix/bin/

echo "DROP DATABASE IF EXISTS ${DB_NAME};" | eval ${BINPATH}dbaccess - -
echo "CREATE DATABASE ${DB_NAME} IN ${DB_SPACE};" | eval ${BINPATH}dbaccess - -

echo "--> create tables"
eval ${BINPATH}dbaccess ${DB_NAME} ${CONFIGPATH}testdb_tables.sql

echo "ALL DONE"

****** testdb_tables.sql

DROP TABLE IF EXISTS "dwa".ean_n_values;

CREATE TABLE IF NOT EXISTS "dwa".ean_n_values
  (
    ean_n_id bigserial not null,
    iean140 real,
    iean150 smallint,
    iean190 char(4) not null
  );

GRANT ALL ON "dwa".ean_n_values TO PUBLIC;

INSERT INTO "dwa".ean_n_values (iean140, iean150, iean190) VALUES (11, 111, 'aaaa');
INSERT INTO "dwa".ean_n_values (iean140, iean150, iean190) VALUES (12, 112, 'bbbb');
INSERT INTO "dwa".ean_n_values (iean140, iean150, iean190) VALUES (13, 113, 'cccc');
INSERT INTO "dwa".ean_n_values (iean140, iean150, iean190) VALUES (14, 114, 'dddd');
INSERT INTO "dwa".ean_n_values (iean140, iean150, iean190) VALUES (15, 115, 'eeee');
INSERT INTO "dwa".ean_n_values (iean140, iean150, iean190) VALUES (16, 116, 'ffff');
INSERT INTO "dwa".ean_n_values (iean140, iean150, iean190) VALUES (17, 117, 'gggg');
INSERT INTO "dwa".ean_n_values (iean140, iean150, iean190) VALUES (18, 118, 'iiii');
INSERT INTO "dwa".ean_n_values (iean140, iean150, iean190) VALUES (19, 119, 'hhhh');

INSERT INTO "dwa".ean_n_values (ean_n_id, iean140, iean150, iean190) VALUES (100, 11, 111, 'aaaa');
INSERT INTO "dwa".ean_n_values (ean_n_id, iean140, iean150, iean190) VALUES (101, 12, 112, 'bbbb');
INSERT INTO "dwa".ean_n_values (ean_n_id, iean140, iean150, iean190) VALUES (102, 13, 113, 'cccc');
INSERT INTO "dwa".ean_n_values (ean_n_id, iean140, iean150, iean190) VALUES (103, 14, 114, 'dddd');
INSERT INTO "dwa".ean_n_values (ean_n_id, iean140, iean150, iean190) VALUES (104, 15, 115, 'eeee');
INSERT INTO "dwa".ean_n_values (ean_n_id, iean140, iean150, iean190) VALUES (105, 16, 116, 'ffff');
INSERT INTO "dwa".ean_n_values (ean_n_id, iean140, iean150, iean190) VALUES (106, 17, 117, 'gggg');
INSERT INTO "dwa".ean_n_values (ean_n_id, iean140, iean150, iean190) VALUES (107, 18, 118, 'iiii');
INSERT INTO "dwa".ean_n_values (ean_n_id, iean140, iean150, iean190) VALUES (108, 19, 119, 'hhhh');

------------ PostgreSQL part ----------------
create extension informix_fdw;

create server informix_source foreign data wrapper informix_fdw options (informixdir '/opt/ibm/informix/client', informixserver 'informix');

create user mapping for postgres server informix_source options( username 'informix', password 'in4mix');

create schema if not exists remote_testdb;

drop foreign table if exists remote_testdb.ean_n_values;

import foreign schema dwa from server informix_source into remote_testdb options (import_default 'true', database 'testdb', client_locale 'en_US.utf8');

select pg_sleep(5); -- to give db time to finish everything

select 'ean_n_values.ean_n_id' as table_column, min(ean_n_id), max(ean_n_id) from remote_testdb.ean_n_values ;

--------------------------------------------
And that last select give me that error. If I change infomix type to bigint, all works as expected.

**Comment by psoo** [comment]
Okay, i know now what's wrong: `ifx_conv.c:convertIfxInt()` and `ifx_connect.ec:ifxGetColumnAttributes()` get the mapping from Informix `BIGSERIAL` type wrong.

Currently, we map this type to the ESQL/C specific type `ifx_int8_t`, which is wrong. The real mapping should be to `bigint` which is identified with `CBIGINTTYPE` to the `SQLDA` structure.

I will prepare a fix and a new release tarball shortly.

**Comment by psoo** [comment]
Fix pushed and release tarball for `REL0_6_1` created. Please test

**Comment by JosefMachytka-credativ** [comment]
Amazing, thank you very much, all works! I tested it with PostgreSQL 12,13 and 15, no problems found.
